#!/usr/bin/python
import sys, os, re, subprocess

packages = 'atk cairo expat fftw fontconfig freetype gdk-pixbuf gettext glib2 gtk2 gtkglext iconv jasper libjpeg libpng libxml2 pango pixman zlib'

nargs = len(sys.argv)
if nargs > 2 or nargs == 2 and sys.argv[1] in ('-h', '--help'):
    print 'copysysfiles [setup]'
    sys.exit(0)

if nargs == 2:
    setupfile = sys.argv[1]
else:
    setupfile = 'setup'

if not os.access(setupfile, os.R_OK):
    sys.stderr.write('Cannot find setup file %s.\n' % setupfile)
    sys.exit(1)

for line in file(setupfile):
    m = re.match(r'^(?P<name>\w+)=(?P<value>.*?)\s*$', line)
    if m:
        locals()[m.group('name')] = os.path.expandvars(m.group('value'))

for name in ('target_prefix', 'mingw32_prefix'):
    if name not in locals():
        sys.stderr.write('Cannot find %s in %s.\n' % (name, setupfile))
        sys.exit(1)

pkglist = ['mingw32-%s' % x for x in packages.split()]
p = subprocess.Popen(['rpm', '-q', '--qf='] + pkglist,
                     stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
p.wait()
if p.returncode:
    sys.stderr.write(p.stdout.read())
    sys.exit(1)
del p

filelist = subprocess.Popen(['rpm', '-ql'] + pkglist,
                            stdout=subprocess.PIPE).communicate()[0]

for filename in sorted(set(filelist.split())):
    if not filename.startswith(mingw32_prefix):
        continue
    if not os.path.isfile(filename):
        continue
    if filename.endswith('.a') or filename.endswith('.la'):
        continue
    basefile = filename[len(mingw32_prefix)+1:]
    dirname = os.path.join(target_prefix, os.path.dirname(basefile))
    if not os.path.isdir(dirname):
        os.makedirs(dirname)
    targetfile = os.path.join(target_prefix, basefile)
    if os.path.islink(targetfile):
        if os.readlink(targetfile) == filename:
            continue
        os.unlink(targetfile)
    os.symlink(filename, targetfile)
